services:
  db:
    image: postgres:17
    container_name: marcarquadra_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marcarquadra_postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: marcarquadra_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - marcarquadra_postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data: {}
  pgadmin_data: {}

networks:
  marcarquadra_postgres:
    driver: bridge
